apiVersion: apps/v1
kind: Deployment
metadata:
  name: brainwave
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: brainwave
  template:
    metadata:
      labels:
        app: brainwave
    spec:
      containers:
      - name: brainwave-container
        image: mouhanedakermi/react-app:1.0.0-16
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "development"
