apiVersion: v1
kind: Service
metadata:
  name: brainwave-service
  namespace: default
spec:
  type: NodePort 
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30008
  selector:
    app: brainwave
